# Q8 - Keyword Monoalphabetic Cipher
# Keyword: CIPHER
# Cipher alphabet is generated by writing the keyword followed by
# unused letters in normal alphabetical order.

import string

keyword = "CIPHER"

def make_cipher_alphabet(keyword):
    result = []
    for ch in keyword.upper() + string.ascii_uppercase:
        if ch not in result:
            result.append(ch)
    return ''.join(result)

cipher_alphabet = make_cipher_alphabet(keyword)
plain_alphabet = string.ascii_uppercase

print("Plain : ", plain_alphabet)
print("Cipher: ", cipher_alphabet)

encrypt_table = dict(zip(plain_alphabet, cipher_alphabet))
decrypt_table = dict(zip(cipher_alphabet, plain_alphabet))

def encrypt(text):
    result = []
    for ch in text:
        if ch.upper() in encrypt_table:
            out = encrypt_table[ch.upper()]
            result.append(out if ch.isupper() else out.lower())
        else:
            result.append(ch)
    return ''.join(result)

def decrypt(text):
    result = []
    for ch in text:
        if ch.upper() in decrypt_table:
            out = decrypt_table[ch.upper()]
            result.append(out if ch.isupper() else out.lower())
        else:
            result.append(ch)
    return ''.join(result)

message = input("\nEnter plaintext to encrypt: ")
ciphertext = encrypt(message)
print("Ciphertext:", ciphertext)

choice = input("\nEnter ciphertext to decrypt (or press Enter to skip): ")
if choice:
    print("Plaintext:", decrypt(choice))
